#!/bin/sh -e

export BL31="/boot/bl31.elf"

make rockpro64-rk3399_defconfig
make

# Install files
mkdir -p "$1/boot"
install -Dm600 idbloader.img "$1/boot/"
install -Dm600 u-boot.itb    "$1/boot/"
install -Dm600 tools/mkimage "$1/boot/"
install -Dm600 boot.txt      "$1/boot/"
