#!/bin/sh -e

export CFLAGS="-fPIC -O2 $CFLAGS"
export LDFLAGS="-shared $LDFLAGS"

# Patch unneeded in next release.
patch -p1 < libelf-linux.patch

# Generate needed header file.
common/native-elf-format | sed 's/unknown/EM_PPC/g' > common/native-elf-format.h

# Generate needed .c files using m4.
for file in libelf/*.m4; do
    ${M4:-m4} -DSRCDIR=libelf "$file" > "${file%%.m4}.c"
done

# Create all objects (.o).
for file in libelf/*.c; do
    ${CC:-cc} -I./libelf -I./common $CFLAGS $CPPFLAGS -c \
        -o "${file%%.c}.o" "$file"
done

mkdir -p "$1/usr/lib"

# Create shared library.
${CC:-cc} $LDFLAGS $CFLAGS -I./libelf -I./common libelf/*.o \
    -o "$1/usr/lib/libelf.so.1"

# Create static library.
${AR:-ar} -rc "$1/usr/lib/libelf.a" libelf/*.o

# Install remaining headers/files.
ln -sf         libelf.so.1             "$1/usr/lib/libelf.so"
install -Dm644 libelf/libelf.h         "$1/usr/include/libelf.h"
install -Dm644 libelf/gelf.h           "$1/usr/include/gelf.h"
install -Dm644 common/elfdefinitions.h "$1/usr/include/elfdefinitions.h"
