#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# 'rust' checksums files in 'vendor/', but we patch a few.
for vendor in libc openssl-sys; do
    sed -i 's/\("files":{\)[^}]*/\1/' "vendor/$vendor/.cargo-checksum.json"
done

cat > config.toml <<EOF
[llvm]
link-shared = true

[build]
build  = "aarch64-unknown-linux-musl"
host   = [ "aarch64-unknown-linux-musl" ]
target = [ "aarch64-unknown-linux-musl" ]

docs           = false
compiler-docs  = false
extended       = true
tools          = ["cargo"]
submodules     = false
python         = "python3"
locked-deps    = true
vendor         = true
sanitizers     = false
profiler       = false
rustc          = "$PWD/aarch64/bin/rustc"
cargo          = "$PWD/aarch64/bin/cargo"
local-rebuild  = true

[install]
prefix = "/usr"

[rust]
channel          = "stable"
rpath            = true
codegen-units    = 1
debuginfo-level  = 0
debug            = false
backtrace        = false
jemalloc         = false
debug-assertions = false
codegen-tests    = false

[target.aarch64-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
crt-static  = false

[dist]
missing-tools = true
EOF

export DESTDIR="$1"

python3 ./x.py build -j 4
python3 ./x.py install

rm -rf "$1/usr/lib/rustlib/src/"
