#!/bin/sh -e

patch -p1 < musl.patch

# 'rust' checksums files in 'vendor/', but we patch a few files.
for vendor in libc openssl-sys; do
    sed -i 's/\("files":{\)[^}]*/\1/' "vendor/$vendor/.cargo-checksum.json"
done

export LD_LIBRARY_PATH=$(pwd)/usr/lib:$LD_LIBRARY_PATH

cat > config.toml <<EOF
[llvm]
link-shared = true

[build]
build = "aarch64-unknown-linux-musl"
host = [ "aarch64-unknown-linux-musl" ]
target = [ "aarch64-unknown-linux-musl" ]
docs = false
extended = true
submodules = false
python = "python3"
locked-deps = true
vendor = true
rustc = "$(pwd)/usr/bin/rustc"
cargo = "$(pwd)/usr/bin/cargo"

[install]
prefix = "/usr"

[rust]
channel = "stable"
rpath = false
codegen-units = 1
debuginfo-level = 0
backtrace = false
jemalloc = false
codegen-tests = false

[target.aarch64-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
crt-static = false
EOF

python3 ./x.py build -j2
DESTDIR="$1" python3 ./x.py install
