#!/bin/sh -e

#for patch in *.patch; do
#    patch -p1 < "$patch"
#done

export BL31="/boot/bl31.elf"

find . -iname "*pine*"

make pinebook-pro-rk3399_defconfig
make

# Install files
mkdir -p "$1/boot"
mkdir -p "$1/usr/bin"
install -Dm600 idbloader.img "$1/boot/"
install -Dm600 u-boot.itb    "$1/boot/"
install -Dm600 boot.txt      "$1/boot/"
install -Dm755 tools/mkimage "$1/usr/bin/"
