#!/bin/sh -e

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH=$PATH:$PWD

# mkdir -p /usr/lib/arm-none-eabi

./configure \
    --prefix=/usr/lib/arm-none-eabi \
    --build=aarch64-linux-musl \
    --host=aarch64-linux-musl \
    --target=arm-none-eabi \
    --disable-multilib \
    --disable-nls \
    --disable-werror \
    --with-mmap \
    --with-system-zlib

make
make DESTDIR="$1" install
